# Grant OPA/kube-mgmt read-only access to resources. This lets kube-mgmt
# list configmaps to be loaded into OPA as policies.
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kelon-viewer
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: Group
    name: system:serviceaccounts:kelon
    apiGroup: rbac.authorization.k8s.io
---
# Create kelon namespace
kind: Namespace
apiVersion: "v1"
metadata:
   name: kelon
   labels:
     name: kelon
---
# Define role for OPA/kube-mgmt to update configmaps with policy status.
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: kelon
  name: configmap-modifier
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["update", "patch"]
---
# Grant OPA/kube-mgmt role defined above.
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: kelon
  name: opa-configmap-modifier
roleRef:
  kind: Role
  name: configmap-modifier
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: Group
    name: system:serviceaccounts:kelon
    apiGroup: rbac.authorization.k8s.io
---
# Deploy OPA and kube-mgmt.
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kelon
  namespace: kelon
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kelon
    spec:
      containers:
        - name: kelon
          image: docker.pkg.github.com/foundato/kelon/kelon:ffbef2f
          args:
            - "--opa-conf=/conf/opa.yml"
            - "--api-conf=/conf/api.yml"
            - "--datastore-conf=/conf/datastore.yml"
            - "--rego-dir=/policies"
            - "--config-watcher-path=/policies"
          ports:
            - name: http
              containerPort: 8181
          volumeMounts:
            - name: config-volume
              mountPath: /conf
            - name: policy-volume
              mountPath: /policies
            - name: call-operands-volume
              mountPath: /call-operands
        - name: kube-mgmt
          image: openpolicyagent/kube-mgmt:0.10
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: config-volume
          configMap:
            name: kelon-configs
        - name: policy-volume
          configMap:
            name: kelon-policies
        - name: call-operands-volume
          configMap:
            name: call-operands